// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers'

/**
 * @constructor
 */
export class Geometry {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Geometry
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Geometry {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Geometry= obj
   * @returns Geometry
   */
  static getRootAsGeometry(bb: flatbuffers.ByteBuffer, obj?: Geometry): Geometry {
    return (obj || new Geometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Geometry= obj
   * @returns Geometry
   */
  static getSizePrefixedRootAsGeometry(bb: flatbuffers.ByteBuffer, obj?: Geometry): Geometry {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Geometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param number index
   * @returns number
   */
  vertices(index: number): number | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0
  }

  /**
   * @returns number
   */
  verticesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @returns Float32Array
   */
  verticesArray(): Float32Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset
      ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset))
      : null
  }

  /**
   * @param number index
   * @returns number
   */
  normals(index: number): number | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0
  }

  /**
   * @returns number
   */
  normalsLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @returns Float32Array
   */
  normalsArray(): Float32Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset
      ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset))
      : null
  }

  /**
   * @param number index
   * @returns number
   */
  indices(index: number): number | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0
  }

  /**
   * @returns number
   */
  indicesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @returns Uint32Array
   */
  indicesArray(): Uint32Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset
      ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset))
      : null
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startGeometry(builder: flatbuffers.Builder) {
    builder.startObject(3)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset verticesOffset
   */
  static addVertices(builder: flatbuffers.Builder, verticesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, verticesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<number> data
   * @returns flatbuffers.Offset
   */
  static createVerticesVector(builder: flatbuffers.Builder, data: number[] | Float32Array): flatbuffers.Offset
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createVerticesVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset
  static createVerticesVector(builder: flatbuffers.Builder, data: number[] | Float32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addFloat32(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startVerticesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset normalsOffset
   */
  static addNormals(builder: flatbuffers.Builder, normalsOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, normalsOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<number> data
   * @returns flatbuffers.Offset
   */
  static createNormalsVector(builder: flatbuffers.Builder, data: number[] | Float32Array): flatbuffers.Offset
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createNormalsVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset
  static createNormalsVector(builder: flatbuffers.Builder, data: number[] | Float32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addFloat32(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startNormalsVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset indicesOffset
   */
  static addIndices(builder: flatbuffers.Builder, indicesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, indicesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<number> data
   * @returns flatbuffers.Offset
   */
  static createIndicesVector(builder: flatbuffers.Builder, data: number[] | Uint32Array): flatbuffers.Offset
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createIndicesVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset
  static createIndicesVector(builder: flatbuffers.Builder, data: number[] | Uint32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addInt32(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startIndicesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endGeometry(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // vertices
    builder.requiredField(offset, 6) // normals
    builder.requiredField(offset, 8) // indices
    return offset
  }

  static createGeometry(
    builder: flatbuffers.Builder,
    verticesOffset: flatbuffers.Offset,
    normalsOffset: flatbuffers.Offset,
    indicesOffset: flatbuffers.Offset,
  ): flatbuffers.Offset {
    Geometry.startGeometry(builder)
    Geometry.addVertices(builder, verticesOffset)
    Geometry.addNormals(builder, normalsOffset)
    Geometry.addIndices(builder, indicesOffset)
    return Geometry.endGeometry(builder)
  }
}
/**
 * @constructor
 */
export class Material {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Material
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Material {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Material= obj
   * @returns Material
   */
  static getRootAsMaterial(bb: flatbuffers.ByteBuffer, obj?: Material): Material {
    return (obj || new Material()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Material= obj
   * @returns Material
   */
  static getSizePrefixedRootAsMaterial(bb: flatbuffers.ByteBuffer, obj?: Material): Material {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Material()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @returns number
   */
  opacity(): number {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startMaterial(builder: flatbuffers.Builder) {
    builder.startObject(1)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number opacity
   */
  static addOpacity(builder: flatbuffers.Builder, opacity: number) {
    builder.addFieldFloat32(0, opacity, 0.0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endMaterial(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    return offset
  }

  static createMaterial(builder: flatbuffers.Builder, opacity: number): flatbuffers.Offset {
    Material.startMaterial(builder)
    Material.addOpacity(builder, opacity)
    return Material.endMaterial(builder)
  }
}
/**
 * @constructor
 */
export class Color {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Color
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Color {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Color= obj
   * @returns Color
   */
  static getRootAsColor(bb: flatbuffers.ByteBuffer, obj?: Color): Color {
    return (obj || new Color()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Color= obj
   * @returns Color
   */
  static getSizePrefixedRootAsColor(bb: flatbuffers.ByteBuffer, obj?: Color): Color {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Color()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @returns number
   */
  r(): number {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0
  }

  /**
   * @returns number
   */
  g(): number {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0
  }

  /**
   * @returns number
   */
  b(): number {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startColor(builder: flatbuffers.Builder) {
    builder.startObject(3)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number r
   */
  static addR(builder: flatbuffers.Builder, r: number) {
    builder.addFieldFloat32(0, r, 0.0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number g
   */
  static addG(builder: flatbuffers.Builder, g: number) {
    builder.addFieldFloat32(1, g, 0.0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number b
   */
  static addB(builder: flatbuffers.Builder, b: number) {
    builder.addFieldFloat32(2, b, 0.0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endColor(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    return offset
  }

  static createColor(builder: flatbuffers.Builder, r: number, g: number, b: number): flatbuffers.Offset {
    Color.startColor(builder)
    Color.addR(builder, r)
    Color.addG(builder, g)
    Color.addB(builder, b)
    return Color.endColor(builder)
  }
}
/**
 * @constructor
 */
export class MeshInstance {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns MeshInstance
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): MeshInstance {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param MeshInstance= obj
   * @returns MeshInstance
   */
  static getRootAsMeshInstance(bb: flatbuffers.ByteBuffer, obj?: MeshInstance): MeshInstance {
    return (obj || new MeshInstance()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param MeshInstance= obj
   * @returns MeshInstance
   */
  static getSizePrefixedRootAsMeshInstance(bb: flatbuffers.ByteBuffer, obj?: MeshInstance): MeshInstance {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new MeshInstance()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  id(): string | null
  id(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  id(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @returns flatbuffers.Long
   */
  expressId(): flatbuffers.Long {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0)
  }

  /**
   * @param number index
   * @returns number
   */
  transformationMatrix(index: number): number | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0
  }

  /**
   * @returns number
   */
  transformationMatrixLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @returns Float32Array
   */
  transformationMatrixArray(): Float32Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset
      ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset))
      : null
  }

  /**
   * @param Color= obj
   * @returns Color|null
   */
  color(obj?: Color): Color | null {
    var offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? (obj || new Color()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startMeshInstance(builder: flatbuffers.Builder) {
    builder.startObject(4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset idOffset
   */
  static addId(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, idOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Long expressId
   */
  static addExpressId(builder: flatbuffers.Builder, expressId: flatbuffers.Long) {
    builder.addFieldInt64(1, expressId, builder.createLong(0, 0))
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset transformationMatrixOffset
   */
  static addTransformationMatrix(builder: flatbuffers.Builder, transformationMatrixOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, transformationMatrixOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<number> data
   * @returns flatbuffers.Offset
   */
  static createTransformationMatrixVector(builder: flatbuffers.Builder, data: number[] | Float32Array): flatbuffers.Offset
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createTransformationMatrixVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset
  static createTransformationMatrixVector(builder: flatbuffers.Builder, data: number[] | Float32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addFloat32(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startTransformationMatrixVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset colorOffset
   */
  static addColor(builder: flatbuffers.Builder, colorOffset: flatbuffers.Offset) {
    builder.addFieldOffset(3, colorOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endMeshInstance(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // id
    builder.requiredField(offset, 8) // transformation_matrix
    builder.requiredField(offset, 10) // color
    return offset
  }
}
/**
 * @constructor
 */
export class InstancedMesh {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns InstancedMesh
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): InstancedMesh {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param InstancedMesh= obj
   * @returns InstancedMesh
   */
  static getRootAsInstancedMesh(bb: flatbuffers.ByteBuffer, obj?: InstancedMesh): InstancedMesh {
    return (obj || new InstancedMesh()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param InstancedMesh= obj
   * @returns InstancedMesh
   */
  static getSizePrefixedRootAsInstancedMesh(bb: flatbuffers.ByteBuffer, obj?: InstancedMesh): InstancedMesh {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new InstancedMesh()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  id(): string | null
  id(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  id(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param Geometry= obj
   * @returns Geometry|null
   */
  geometry(obj?: Geometry): Geometry | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? (obj || new Geometry()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param Material= obj
   * @returns Material|null
   */
  material(obj?: Material): Material | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? (obj || new Material()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param number index
   * @param MeshInstance= obj
   * @returns MeshInstance
   */
  instances(index: number, obj?: MeshInstance): MeshInstance | null {
    var offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? (obj || new MeshInstance()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  instancesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startInstancedMesh(builder: flatbuffers.Builder) {
    builder.startObject(4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset idOffset
   */
  static addId(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, idOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset geometryOffset
   */
  static addGeometry(builder: flatbuffers.Builder, geometryOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, geometryOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset materialOffset
   */
  static addMaterial(builder: flatbuffers.Builder, materialOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, materialOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset instancesOffset
   */
  static addInstances(builder: flatbuffers.Builder, instancesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(3, instancesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createInstancesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startInstancesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endInstancedMesh(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // id
    builder.requiredField(offset, 6) // geometry
    builder.requiredField(offset, 8) // material
    builder.requiredField(offset, 10) // instances
    return offset
  }
}
/**
 * @constructor
 */
export class Group {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Group
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Group {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Group= obj
   * @returns Group
   */
  static getRootAsGroup(bb: flatbuffers.ByteBuffer, obj?: Group): Group {
    return (obj || new Group()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Group= obj
   * @returns Group
   */
  static getSizePrefixedRootAsGroup(bb: flatbuffers.ByteBuffer, obj?: Group): Group {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Group()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param number index
   * @param InstancedMesh= obj
   * @returns InstancedMesh
   */
  instancedMeshes(index: number, obj?: InstancedMesh): InstancedMesh | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? (obj || new InstancedMesh()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  instancedMeshesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startGroup(builder: flatbuffers.Builder) {
    builder.startObject(1)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset instancedMeshesOffset
   */
  static addInstancedMeshes(builder: flatbuffers.Builder, instancedMeshesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, instancedMeshesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createInstancedMeshesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startInstancedMeshesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endGroup(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // instanced_meshes
    return offset
  }

  static createGroup(builder: flatbuffers.Builder, instancedMeshesOffset: flatbuffers.Offset): flatbuffers.Offset {
    Group.startGroup(builder)
    Group.addInstancedMeshes(builder, instancedMeshesOffset)
    return Group.endGroup(builder)
  }
}
/**
 * @constructor
 */
export class Property {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Property
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Property {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Property= obj
   * @returns Property
   */
  static getRootAsProperty(bb: flatbuffers.ByteBuffer, obj?: Property): Property {
    return (obj || new Property()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Property= obj
   * @returns Property
   */
  static getSizePrefixedRootAsProperty(bb: flatbuffers.ByteBuffer, obj?: Property): Property {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Property()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  key(): string | null
  key(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  key(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  value(): string | null
  value(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  value(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startProperty(builder: flatbuffers.Builder) {
    builder.startObject(2)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset keyOffset
   */
  static addKey(builder: flatbuffers.Builder, keyOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, keyOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset valueOffset
   */
  static addValue(builder: flatbuffers.Builder, valueOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, valueOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endProperty(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // key
    builder.requiredField(offset, 6) // value
    return offset
  }

  static createProperty(builder: flatbuffers.Builder, keyOffset: flatbuffers.Offset, valueOffset: flatbuffers.Offset): flatbuffers.Offset {
    Property.startProperty(builder)
    Property.addKey(builder, keyOffset)
    Property.addValue(builder, valueOffset)
    return Property.endProperty(builder)
  }
}
/**
 * @constructor
 */
export class EntityInstance {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns EntityInstance
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): EntityInstance {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param EntityInstance= obj
   * @returns EntityInstance
   */
  static getRootAsEntityInstance(bb: flatbuffers.ByteBuffer, obj?: EntityInstance): EntityInstance {
    return (obj || new EntityInstance()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param EntityInstance= obj
   * @returns EntityInstance
   */
  static getSizePrefixedRootAsEntityInstance(bb: flatbuffers.ByteBuffer, obj?: EntityInstance): EntityInstance {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new EntityInstance()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @returns flatbuffers.Long
   */
  expressId(): flatbuffers.Long {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  type(): string | null
  type(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  type(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param number index
   * @param Property= obj
   * @returns Property
   */
  properties(index: number, obj?: Property): Property | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? (obj || new Property()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  propertiesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startEntityInstance(builder: flatbuffers.Builder) {
    builder.startObject(3)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Long expressId
   */
  static addExpressId(builder: flatbuffers.Builder, expressId: flatbuffers.Long) {
    builder.addFieldInt64(0, expressId, builder.createLong(0, 0))
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset typeOffset
   */
  static addType(builder: flatbuffers.Builder, typeOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, typeOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset propertiesOffset
   */
  static addProperties(builder: flatbuffers.Builder, propertiesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, propertiesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createPropertiesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startPropertiesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endEntityInstance(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 6) // type
    builder.requiredField(offset, 8) // properties
    return offset
  }

  static createEntityInstance(builder: flatbuffers.Builder, expressId: flatbuffers.Long, typeOffset: flatbuffers.Offset, propertiesOffset: flatbuffers.Offset): flatbuffers.Offset {
    EntityInstance.startEntityInstance(builder)
    EntityInstance.addExpressId(builder, expressId)
    EntityInstance.addType(builder, typeOffset)
    EntityInstance.addProperties(builder, propertiesOffset)
    return EntityInstance.endEntityInstance(builder)
  }
}
/**
 * @constructor
 */
export class Metadata {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Metadata
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Metadata {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Metadata= obj
   * @returns Metadata
   */
  static getRootAsMetadata(bb: flatbuffers.ByteBuffer, obj?: Metadata): Metadata {
    return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Metadata= obj
   * @returns Metadata
   */
  static getSizePrefixedRootAsMetadata(bb: flatbuffers.ByteBuffer, obj?: Metadata): Metadata {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  name(): string | null
  name(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  name(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  schema(): string | null
  schema(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  schema(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  creationDate(): string | null
  creationDate(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  creationDate(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  authorName(): string | null
  authorName(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  authorName(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  authorEmail(): string | null
  authorEmail(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  authorEmail(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 12)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  organization(): string | null
  organization(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  organization(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 14)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  preprocessorVersion(): string | null
  preprocessorVersion(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  preprocessorVersion(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 16)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  originatingSystem(): string | null
  originatingSystem(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  originatingSystem(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 18)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  authorization(): string | null
  authorization(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  authorization(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 20)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param number index
   * @param Property= obj
   * @returns Property
   */
  descriptions(index: number, obj?: Property): Property | null {
    var offset = this.bb!.__offset(this.bb_pos, 22)
    return offset ? (obj || new Property()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  descriptionsLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 22)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startMetadata(builder: flatbuffers.Builder) {
    builder.startObject(10)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset nameOffset
   */
  static addName(builder: flatbuffers.Builder, nameOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, nameOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset schemaOffset
   */
  static addSchema(builder: flatbuffers.Builder, schemaOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, schemaOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset creationDateOffset
   */
  static addCreationDate(builder: flatbuffers.Builder, creationDateOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, creationDateOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset authorNameOffset
   */
  static addAuthorName(builder: flatbuffers.Builder, authorNameOffset: flatbuffers.Offset) {
    builder.addFieldOffset(3, authorNameOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset authorEmailOffset
   */
  static addAuthorEmail(builder: flatbuffers.Builder, authorEmailOffset: flatbuffers.Offset) {
    builder.addFieldOffset(4, authorEmailOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset organizationOffset
   */
  static addOrganization(builder: flatbuffers.Builder, organizationOffset: flatbuffers.Offset) {
    builder.addFieldOffset(5, organizationOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset preprocessorVersionOffset
   */
  static addPreprocessorVersion(builder: flatbuffers.Builder, preprocessorVersionOffset: flatbuffers.Offset) {
    builder.addFieldOffset(6, preprocessorVersionOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset originatingSystemOffset
   */
  static addOriginatingSystem(builder: flatbuffers.Builder, originatingSystemOffset: flatbuffers.Offset) {
    builder.addFieldOffset(7, originatingSystemOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset authorizationOffset
   */
  static addAuthorization(builder: flatbuffers.Builder, authorizationOffset: flatbuffers.Offset) {
    builder.addFieldOffset(8, authorizationOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset descriptionsOffset
   */
  static addDescriptions(builder: flatbuffers.Builder, descriptionsOffset: flatbuffers.Offset) {
    builder.addFieldOffset(9, descriptionsOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createDescriptionsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startDescriptionsVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endMetadata(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 6) // schema
    return offset
  }

  static createMetadata(
    builder: flatbuffers.Builder,
    nameOffset: flatbuffers.Offset,
    schemaOffset: flatbuffers.Offset,
    creationDateOffset: flatbuffers.Offset,
    authorNameOffset: flatbuffers.Offset,
    authorEmailOffset: flatbuffers.Offset,
    organizationOffset: flatbuffers.Offset,
    preprocessorVersionOffset: flatbuffers.Offset,
    originatingSystemOffset: flatbuffers.Offset,
    authorizationOffset: flatbuffers.Offset,
    descriptionsOffset: flatbuffers.Offset,
  ): flatbuffers.Offset {
    Metadata.startMetadata(builder)
    Metadata.addName(builder, nameOffset)
    Metadata.addSchema(builder, schemaOffset)
    Metadata.addCreationDate(builder, creationDateOffset)
    Metadata.addAuthorName(builder, authorNameOffset)
    Metadata.addAuthorEmail(builder, authorEmailOffset)
    Metadata.addOrganization(builder, organizationOffset)
    Metadata.addPreprocessorVersion(builder, preprocessorVersionOffset)
    Metadata.addOriginatingSystem(builder, originatingSystemOffset)
    Metadata.addAuthorization(builder, authorizationOffset)
    Metadata.addDescriptions(builder, descriptionsOffset)
    return Metadata.endMetadata(builder)
  }
}
/**
 * @constructor
 */
export class SpatialStructureNode {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns SpatialStructureNode
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): SpatialStructureNode {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param SpatialStructureNode= obj
   * @returns SpatialStructureNode
   */
  static getRootAsSpatialStructureNode(bb: flatbuffers.ByteBuffer, obj?: SpatialStructureNode): SpatialStructureNode {
    return (obj || new SpatialStructureNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param SpatialStructureNode= obj
   * @returns SpatialStructureNode
   */
  static getSizePrefixedRootAsSpatialStructureNode(bb: flatbuffers.ByteBuffer, obj?: SpatialStructureNode): SpatialStructureNode {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new SpatialStructureNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @returns flatbuffers.Long
   */
  expressId(): flatbuffers.Long {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0)
  }

  /**
   * @param number index
   * @param SpatialStructureNode= obj
   * @returns SpatialStructureNode
   */
  children(index: number, obj?: SpatialStructureNode): SpatialStructureNode | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? (obj || new SpatialStructureNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  childrenLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startSpatialStructureNode(builder: flatbuffers.Builder) {
    builder.startObject(2)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Long expressId
   */
  static addExpressId(builder: flatbuffers.Builder, expressId: flatbuffers.Long) {
    builder.addFieldInt64(0, expressId, builder.createLong(0, 0))
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset childrenOffset
   */
  static addChildren(builder: flatbuffers.Builder, childrenOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, childrenOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createChildrenVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startChildrenVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endSpatialStructureNode(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 6) // children
    return offset
  }

  static createSpatialStructureNode(builder: flatbuffers.Builder, expressId: flatbuffers.Long, childrenOffset: flatbuffers.Offset): flatbuffers.Offset {
    SpatialStructureNode.startSpatialStructureNode(builder)
    SpatialStructureNode.addExpressId(builder, expressId)
    SpatialStructureNode.addChildren(builder, childrenOffset)
    return SpatialStructureNode.endSpatialStructureNode(builder)
  }
}
/**
 * @constructor
 */
export class SpatialStructure {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns SpatialStructure
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): SpatialStructure {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param SpatialStructure= obj
   * @returns SpatialStructure
   */
  static getRootAsSpatialStructure(bb: flatbuffers.ByteBuffer, obj?: SpatialStructure): SpatialStructure {
    return (obj || new SpatialStructure()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param SpatialStructure= obj
   * @returns SpatialStructure
   */
  static getSizePrefixedRootAsSpatialStructure(bb: flatbuffers.ByteBuffer, obj?: SpatialStructure): SpatialStructure {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new SpatialStructure()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param SpatialStructureNode= obj
   * @returns SpatialStructureNode|null
   */
  node(obj?: SpatialStructureNode): SpatialStructureNode | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? (obj || new SpatialStructureNode()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startSpatialStructure(builder: flatbuffers.Builder) {
    builder.startObject(1)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset nodeOffset
   */
  static addNode(builder: flatbuffers.Builder, nodeOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, nodeOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endSpatialStructure(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // node
    return offset
  }

  static createSpatialStructure(builder: flatbuffers.Builder, nodeOffset: flatbuffers.Offset): flatbuffers.Offset {
    SpatialStructure.startSpatialStructure(builder)
    SpatialStructure.addNode(builder, nodeOffset)
    return SpatialStructure.endSpatialStructure(builder)
  }
}
/**
 * @constructor
 */
export class Model {
  bb: flatbuffers.ByteBuffer | null = null

  bb_pos: number = 0
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Model
   */
  __init(i: number, bb: flatbuffers.ByteBuffer): Model {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Model= obj
   * @returns Model
   */
  static getRootAsModel(bb: flatbuffers.ByteBuffer, obj?: Model): Model {
    return (obj || new Model()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Model= obj
   * @returns Model
   */
  static getSizePrefixedRootAsModel(bb: flatbuffers.ByteBuffer, obj?: Model): Model {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new Model()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  }

  /**
   * @param flatbuffers.Encoding= optionalEncoding
   * @returns string|Uint8Array|null
   */
  id(): string | null
  id(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  id(optionalEncoding?: any): string | Uint8Array | null {
    var offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null
  }

  /**
   * @param Group= obj
   * @returns Group|null
   */
  group(obj?: Group): Group | null {
    var offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? (obj || new Group()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param number index
   * @param EntityInstance= obj
   * @returns EntityInstance
   */
  entityInstances(index: number, obj?: EntityInstance): EntityInstance | null {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? (obj || new EntityInstance()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  }

  /**
   * @returns number
   */
  entityInstancesLength(): number {
    var offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  }

  /**
   * @param SpatialStructure= obj
   * @returns SpatialStructure|null
   */
  spatialStructure(obj?: SpatialStructure): SpatialStructure | null {
    var offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? (obj || new SpatialStructure()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param Metadata= obj
   * @returns Metadata|null
   */
  metadata(obj?: Metadata): Metadata | null {
    var offset = this.bb!.__offset(this.bb_pos, 12)
    return offset ? (obj || new Metadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  }

  /**
   * @param flatbuffers.Builder builder
   */
  static startModel(builder: flatbuffers.Builder) {
    builder.startObject(5)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset idOffset
   */
  static addId(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, idOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset groupOffset
   */
  static addGroup(builder: flatbuffers.Builder, groupOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, groupOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset entityInstancesOffset
   */
  static addEntityInstances(builder: flatbuffers.Builder, entityInstancesOffset: flatbuffers.Offset) {
    builder.addFieldOffset(2, entityInstancesOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param Array.<flatbuffers.Offset> data
   * @returns flatbuffers.Offset
   */
  static createEntityInstancesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (var i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  }

  /**
   * @param flatbuffers.Builder builder
   * @param number numElems
   */
  static startEntityInstancesVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset spatialStructureOffset
   */
  static addSpatialStructure(builder: flatbuffers.Builder, spatialStructureOffset: flatbuffers.Offset) {
    builder.addFieldOffset(3, spatialStructureOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset metadataOffset
   */
  static addMetadata(builder: flatbuffers.Builder, metadataOffset: flatbuffers.Offset) {
    builder.addFieldOffset(4, metadataOffset, 0)
  }

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endModel(builder: flatbuffers.Builder): flatbuffers.Offset {
    var offset = builder.endObject()
    builder.requiredField(offset, 4) // id
    builder.requiredField(offset, 6) // group
    builder.requiredField(offset, 8) // entity_instances
    builder.requiredField(offset, 10) // spatial_structure
    builder.requiredField(offset, 12) // metadata
    return offset
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset offset
   */
  static finishModelBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset)
  }

  /**
   * @param flatbuffers.Builder builder
   * @param flatbuffers.Offset offset
   */
  static finishSizePrefixedModelBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset, undefined, true)
  }
}
